### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by rev9dev** [DominatorDev/WarZoneDominator#1]
Seems to be a RAT, Do not run the app.

**Comment by DominatorDev** [comment]
If you have any problems, you can contact me on discord

d0minat0r8

**Comment by rev9dev** [comment]
How can belive your the real owner of Dominator Cheat?

**Comment by Whitesun123** [comment]
> If you have any problems, you can contact me on discord
> 
> d0minat0r8

Please fix your trash RAT, its not working nor is it properly sending TCP requests. Please fix your INFO stealer before reposting.
